# Generated by Django 5.1.6 on 2025-03-18 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_customuser_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='external_links',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='api.topic'),
        ),
        migrations.AlterField(
            model_name='lessoncompletion',
            name='completed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lessoncompletion',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lesson'),
        ),
        migrations.AlterField(
            model_name='lessoncompletion',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topic',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='topic',
            name='quiz_pass_mark',
            field=models.IntegerField(default=70),
        ),
        migrations.AlterField(
            model_name='topic',
            name='quiz_required_lessons',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='lessoncompletion',
            unique_together={('student', 'lesson')},
        ),
    ]
