# Generated by Django 5.1.6 on 2025-03-18 21:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_topic_description_alter_lessoncompletion_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='pass_mark',
            field=models.IntegerField(default=70, help_text='Minimum percentage required to pass', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time_limit',
            field=models.PositiveIntegerField(default=30, help_text='Time limit in minutes', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
