# Generated by Django 5.1.6 on 2025-03-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_quizattempt_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
