# Generated by Django 5.1.6 on 2026-01-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='security_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='security_question',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
